rvm:
  - 2.1.*
  - 2.2.*
  - 2.3.0
  - 2.4.0
gemfile:
  - Gemfile
  - Gemfile.fluentd.0.12
  - Gemfile.fluentd.0.10
matrix:
  exclude:
    - rvm: 2.4.0
      gemfile: Gemfile.fluentd.0.10
before_install: gem update bundler
